# -*- coding: utf-8 -*-
"""dkpc_ali.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tVPSiUar59d1KeGDzGmVGQqLmZyucDHa
"""

import pandas as pd

csv_1 = pd.read_csv('data1.csv')
csv_2 = pd.read_csv('data2.csv')

merged = csv_1.merge(csv_2, on='id')
merged.to_csv('output.csv', sep=',', header=True, index=False)